kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-user-cluster-role-binding 
subjects:
- kind: User 
  name: docker2014.se.gzst.qihoo.net 
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin 
  apiGroup: rbac.authorization.k8s.io
