apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    alpha.istio.io/sidecar: injected(deprecated)
    status.sidecar.istio.io: injected-version-root@e576b27c22f9-0.2.1-d6a3290
  creationTimestamp: null
  name: ratings-v1
  namespace: default
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: injected(deprecated)
        status.sidecar.istio.io: injected-version-root@e576b27c22f9-0.2.1-d6a3290
      creationTimestamp: null
      labels:
        app: ratings
        version: v1
    spec:
      containers:
      - image: r.qihoo.cloud/mirror/istio/example/bookinfo-ratings:v1
        imagePullPolicy: IfNotPresent
        name: ratings
        ports:
        - containerPort: 9080
        resources: {}
      - args:
        - proxy
        - sidecar
        - -v
        - "2"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: r.qihoo.cloud/mirror/istio/proxy_debug:0.2.1
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/config
          name: istio-config
          readOnly: true
        - mountPath: /etc/istio/proxy
          name: istio-envoy
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        image: r.qihoo.cloud/mirror/istio/proxy_init:0.2.1
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - CAP_NET_ADMIN
          privileged: true
      - args:
        - -c
        - sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t && ulimit -c
          unlimited
        command:
        - /bin/sh
        image: alpine
        imagePullPolicy: IfNotPresent
        name: enable-core-dump
        resources: {}
        securityContext:
          privileged: true
      volumes:
      - configMap:
          name: istio
        name: istio-config
      - emptyDir:
          medium: Memory
          sizeLimit: "0"
        name: istio-envoy
status: {}
---
