---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'istio-mesh'
      scrape_interval: 5s
      static_configs:
      - targets: ['istio-mixer.default.svc.qihoo.cloud:42422']
    - job_name: 'envoy'
      scrape_interval: 5s
      static_configs:
      - targets: ['istio-mixer.default.svc.qihoo.cloud:9102']
    - job_name: 'mixer'
      scrape_interval: 5s
      static_configs:
      - targets: ['istio-mixer.default.svc.qihoo.cloud:9093']
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: istio-prometheus
  name: istio-prometheus
spec:
  externalIPs:
  - 10.168.96.52
  - 10.168.96.51
  - 10.168.96.50
  type: ClusterIP 
  selector:
    app: istio-prometheus
  ports:
  - name: prometheus
    protocol: TCP
    targetPort: 9090 
    port: 30301 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-prometheus
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: ignore
      name: istio-prometheus
      labels:
        app: istio-prometheus
    spec:
      containers:
      - name: prometheus
        image: r.qihoo.cloud/mirror/istio/prometheus:v1.1.1 
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: istio-prometheus
