---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-servicegraph
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: ignore
      labels:
        app: istio-servicegraph
    spec:
      containers:
      - name: servicegraph
        # image: gcr.io/istio-testing/servicegraph:latest
        image: r.qihoo.cloud/mirror/istio/servicegraph:testing 
        ports:
          - containerPort: 8088
        args:
        - --prometheusAddr=http://istio-prometheus.default.svc.qihoo.cloud:30301
---
apiVersion: v1
kind: Service
metadata:
  name: istio-servicegraph
spec:
  externalIPs:
  - 10.168.96.52
  - 10.168.96.51
  - 10.168.96.50
  type: ClusterIP 
  ports:
  - name: http
    targetPort: 8088 
    port: 30302 
  selector:
    app: istio-servicegraph
---
